<?php

namespace Asin;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Module\Infrastructure\Product\AsinEloquentRepository;
use Tests\TestCase;

class SaveAsinActionTest extends TestCase
{

    use RefreshDatabase;

    private AsinEloquentRepository $asinRepository;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->asinRepository = new AsinEloquentRepository();
    }

    public function test_can_save_asin() {
        $user = User::factory()->create();
        $response = $this->actingAs($user)->post('/asin/save', ['asin' => 'B072BWF93B']);
        $response->assertJson(['isSave' => true]);
    }

}
