<?php

namespace Login;

use Module\Auth\useCases\Login\LoginCommand;
use Module\Auth\useCases\Login\LoginUser;
use Module\Infrastructure\Auth\AuthRepositoryInMemory;
use Tests\TestCase;

class LoginTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_user_can_login() {
        $email = 'test@gmail.com';
        $password = '123456';

        $loginCommand = new LoginCommand();
        $loginCommand->email = $email;
        $loginCommand->password = $password;

        $authRepository = new AuthRepositoryInMemory();
        $loginUser = new LoginUser($authRepository);

        $loginResponse = $loginUser->__invoke($loginCommand);
        $this->assertTrue($loginResponse->isLogged);
        $this->assertEquals('Utilisateur connecté', $loginResponse->message);
    }

}
