<?php

namespace Tests\Unit\Login;

use Module\Auth\Exceptions\ErrorAuthException;
use Module\Auth\useCases\Login\LoginCommand;
use Module\Auth\useCases\Login\LoginUser;
use Module\Infrastructure\Auth\AuthRepositoryInMemory;
use Tests\TestCase;

class LoginTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_user_can_login() {

        $loginCommand = LoginCommandBuilder::asLogin()->build();

        $authRepository = new AuthRepositoryInMemory();
        $loginUser = new LoginUser($authRepository);

        $loginResponse = $loginUser->__invoke($loginCommand);
        $this->assertTrue($loginResponse->isLogged);
        $this->assertEquals('Utilisateur connecté', $loginResponse->message);
    }

    public function test_user_login_with_wrong_credentials() {
        $loginCommand = LoginCommandBuilder::asLogin()
            ->withEmail('tessdqsdqsd@qsdqsd.qsdqsd')
            ->build();

        $authRepository = new AuthRepositoryInMemory();
        $loginUser = new LoginUser($authRepository);

        $loginResponse = $loginUser->__invoke($loginCommand);
        $this->assertFalse($loginResponse->isLogged);
        $this->assertEquals("Login ou mot de passe incorrect", $loginResponse->message);
    }

    public function test_user_login_with_wrong_password() {
        $loginCommand = LoginCommandBuilder::asLogin()
            ->withPassword('azeazeazeaze')
            ->build();

        $authRepository = new AuthRepositoryInMemory();
        $loginUser = new LoginUser($authRepository);

        $loginResponse = $loginUser->__invoke($loginCommand);
        $this->assertFalse($loginResponse->isLogged);
        $this->assertEquals("Votre mot de passe  n'est pas valide", $loginResponse->message);
    }

    public function test_user_login_with_invalid_email() {
        $loginCommand = LoginCommandBuilder::asLogin()
            ->withEmail('qdsdsfsdfsdf')
            ->build();

        $authRepository = new AuthRepositoryInMemory();
        $loginUser = new LoginUser($authRepository);

        $this->expectException(ErrorAuthException::class);
        $this->expectExceptionMessage("Cet adresse email : $loginCommand->email n'est pas valide");
        $loginResponse = $loginUser->__invoke($loginCommand);
    }

}
