<?php

namespace Tests\Feature\Login;

use Tests\TestCase;

class LoginUserActionTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_user_can_login() {
        $response = $this->post('/login', ['email' => 'test@gmail.com', 'password' => '123456']);
        $response->assertStatus(201)
            ->assertJson(
                ['status' => true]
            );
    }
}
