<?php

namespace Tests\Feature\Login;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class LoginUserActionTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        User::factory()->create(['email' => 'test@gmail.com', 'password' => '123456']);
    }

    public function test_user_can_login() {
        $response = $this->post('/login', ['email' => 'test@gmail.com', 'password' => '123456']);
        $response->assertStatus(200)
            ->assertJson(
                ['message' => 'Utilisateur connecté', 'isLogged' => true]
            );
    }

    public function test_user_can_login_with_wrong_email() {
        $response = $this->post('/login', ['email' => 'testgmail.com', 'password' => '123456']);
        $response->assertStatus(200)
            ->assertJson(
                ['message' => "Cet adresse email : testgmail.com n'est pas valide", 'isLogged' => false]
            );
    }

}
